config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:new, :create, :index]
  resources :subscribers, only: [:new, :create, :index]

  get '/weeklies', to: 'weeklies#index'
  
  root to: 'posts#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title, :url

  scope :not_sent, -> { where(sent_on: nil) }
  scope :sent, -> { where.not(sent_on: nil) }
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.email_list
    pluck(:email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @sent_posts = Post.sent.order(id: :desc)
    @not_sent_posts = Post.not_sent.order(id: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to new_post_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  private

  def post_params
    params.fetch(:post).permit(:title, :url, :description)
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
    @subscribers = Subscriber.all
  end

  def new
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)

    if @subscriber.save
      redirect_to new_post_path, notice: 'Subscription created!'
    else
      render :new
    end
  end

  def unsubscribe
    subscriber = Subscriber.find_by(email: params[:unsubscribe][:email])

    if subscriber
      UnsubscribeMailSender.call(subscriber)
      redirect_to new_post_path, notice: 'Check your email to find your unsubscribe url!'
    else
      redirect_to new_post_path, notice: 'Email not found!'
    end
  end

  def cancel_subscription
    subscriber = Subscriber.find_by(delete_token: params[:delete_token])
    subscriber.destroy

    redirect_to new_post_path, notice: 'Subscription canceled!'
  end

  private

  def subscriber_params
    params.fetch(:subscriber).permit(:email)
  end
end

app/controllers/weeklies_controller.rb
class WeekliesController < ApplicationController
  Weekly = Struct.new(:date, :posts)

  def index
    posts = Post.all.group_by(&:sent_on)

    @weeklies = posts.map { |date, posts| Weekly.new(date, posts) }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YourWeekly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag(*webpack_asset_paths('application')) %>
  </head>

  <body>
    <div class="notice">
      <%= notice %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <%= link_to post.title, post.url %> <br>
  <%= post.description %><br>
</div>

app/views/posts/_post.text.erb
<%= post.title %>

<%= post.url %>

<%= post.description %>

-----------------------------------------------------------------

app/views/posts/index.html.erb
<div class="center-container">
  <h1>All posts</h1>

  <h2>Posts to be sent on the next weekly</h2>

  <%= render @not_sent_posts %>

  <% if @not_sent_posts.empty? %>
    <p>
      No post submitted yet!
    </p>
  <% end %>

  <h2>Post sent previously</h2>

  <%= render @sent_posts %>

  <% if @sent_posts.empty? %>
    <p>
      No post in this category yet!
    </p>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="center-container">
  <h1>Add a new post</h1>

  <%= render 'form' %>

  <hr>
  <%= link_to new_subscriber_path do %>
    <h2>Not subscribed yet?</h2>
  <% end %>
  <hr>
  <hr>
  <hr>

  <h3>Unsubscribe : (</h2>
  <%= form_for :unsubscribe, url: unsubscribe_path, method: :delete do |f| %>
    <%= f.text_field :email, placeholder: 'Your email' %>
    <%= f.submit 'Unsubscribe' %>
  <% end %>
</div>

app/views/subscribers/_form.html.erb
<%= form_for @subscriber do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@subscriber.errors.count, "error") %> prohibited
        this subscriber from being saved:
      </h2>
      <ul>
        <% @subscriber.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/subscribers/_subscriber.html.erb
<%= subscriber.email %>
<br>
<br>

app/views/subscribers/index.html.erb
<div class="center-container">
  <h1>Subscribers</h1>

  <%= render @subscribers %>
</div>

app/views/subscribers/new.html.erb
<div class="center-container">
  <h1>Subscribe to You Weekly</h1>

  <%= render 'form' %>
</div>

app/views/weeklies/index.html.erb
<div class="center-container">
  <h1>Last weeklies</h1>

  <% @weeklies.each do |weekly| %>
    <h3><%= weekly.date %></h3>

    <% weekly.posts.each do |post| %>
      <%= render post %>
    <% end %>
  <% end %>
</div>